name: A-TO-B:MASTER
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: wjfee/vuepress-deploy@v2.0.3
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: wjfee/wjfee.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn docs:build
        BUILD_DIR: designPattern/.vuepress/dist/
        SOURCE_DIR: designPattern/
