name: A-TO-B:MASTER
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Copy Files
      run: |
        mkdir public 
        cp -r docsify/* public/
    - name: Build
      uses: wjftu/vuepress_1.x_compiler@fix_GA
      env:
        SOURCE_DIR: designPattern designPattern2
        BUILD_SCRIPT: yarn add -D @vuepress/plugin-google-analytics && yarn docs:build
    - name: Deploy
      uses: wjftu/git_push_action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: wjfee/wjfee.github.io
        TARGET_BRANCH: master
        SOURCE_DIR: public
    # - name: Build and Deploy
    #   # uses: wjfee/vuepress-deploy@master
    #   uses: wjfee/vuepress-compiler@master
    #   env:
    #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     TARGET_REPO: wjfee/wjfee.github.io
    #     TARGET_BRANCH: master
    #     BUILD_SCRIPT: yarn && yarn docs:build
    #     # BUILD_DIR: docs/.vuepress/dist
    #     BUILD_DIR: /github/workspace/public
    #     SOURCE_DIR: designPattern designPattern2
